export const COUNTRIES = [
  {
    id: 1,
    name: "Burkina Faso",
    countryCode: "+226",
    flag: require("../assets/burkinafaso.png"),
  },
  {
    id: 2,
    name: "Côte d'Ivoire",
    countryCode: "+225",
    flag: require("../assets/ivoryCoast.png"),
  },
  {
    id: 3,
    name: "Gambia",
    countryCode: "+220",
    flag: require("../assets/gambia.png"),
  },
  {
    id: 4,
    name: "Mali",
    countryCode: "+223",
    flag: require("../assets/mali.png"),
  },
  {
    id: 5,
    name: "Senegal",
    countryCode: "+221",
    flag: require("../assets/senegal.png"),
  },
  {
    id: 6,
    name: "Uganda",
    countryCode: "+256",
    flag: require("../assets/uganda.png"),
  },
];

export const TRANSACTIONS = [
  {
    id: 1,
    type: "withdrawal",
    amount: "1,000",
    fee: "0",
    status: "completed",
    agentName: "DOJ Rabaraba",
    newBalance: "15",
    transactionId: "ATXLJY2KKDCU4",
    date: "Jul 04, 2023",
    dateTime: "Jul 04 2023 7:19 PM",
  },
  {
    id: 2,
    type: "receive",
    amount: "990",
    fee: "10",
    status: "completed",
    newBalance: "1,015",
    transactionId: "TLNLJY2KKDCU4",
    date: "Jul 08, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
  {
    id: 3,
    type: "send",
    amount: "2,000",
    total: "2,020",
    fee: "20",
    status: "completed",
    newBalance: "25",
    transactionId: "TEU7HY2KKDCU4",
    date: "Aug 04, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
  {
    id: 4,
    type: "deposit",
    amount: "2,000",
    fee: "0",
    status: "completed",
    newBalance: "2,045",
    transactionId: "HREIHY2KKDCU4",
    date: "Aug 28, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
  {
    id: 5,
    type: "withdrawal",
    amount: "1,000",
    fee: "0",
    status: "completed",
    agentName: "DOJ Rabaraba",
    newBalance: "15",
    transactionId: "ATXLJY2KKDCU4",
    date: "Jul 04, 2023",
    dateTime: "Jul 04 2023 7:19 PM",
  },
  {
    id: 6,
    type: "receive",
    amount: "990",
    fee: "10",
    status: "completed",
    newBalance: "1,015",
    transactionId: "TLNLJY2KKDCU4",
    date: "Jul 08, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
  {
    id: 7,
    type: "send",
    amount: "2,000",
    total: "2,020",
    fee: "20",
    status: "completed",
    newBalance: "25",
    transactionId: "TEU7HY2KKDCU4",
    date: "Aug 04, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
  {
    id: 8,
    type: "deposit",
    amount: "2,000",
    fee: "0",
    status: "completed",
    newBalance: "2,045",
    transactionId: "HREIHY2KKDCU4",
    date: "Aug 28, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
  {
    id: 9,
    type: "withdrawal",
    amount: "1,000",
    fee: "0",
    status: "completed",
    agentName: "DOJ Rabaraba",
    newBalance: "15",
    transactionId: "ATXLJY2KKDCU4",
    date: "Jul 04, 2023",
    dateTime: "Jul 04 2023 7:19 PM",
  },
  {
    id: 10,
    type: "receive",
    amount: "990",
    fee: "10",
    status: "completed",
    newBalance: "1,015",
    transactionId: "TLNLJY2KKDCU4",
    date: "Jul 08, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
  {
    id: 11,
    type: "send",
    amount: "2,000",
    total: "2,020",
    fee: "20",
    status: "completed",
    newBalance: "25",
    transactionId: "TEU7HY2KKDCU4",
    date: "Aug 04, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
  {
    id: 12,
    type: "deposit",
    amount: "2,000",
    fee: "0",
    status: "completed",
    newBalance: "2,045",
    transactionId: "HREIHY2KKDCU4",
    date: "Aug 28, 2023",
    dateTime: "Jul 08 2023 9:20 PM",
  },
];
